spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Text
    username: root
    password: 13468724917qkm,
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
